// @ts-nocheck
export const DIMENSIONS = {
  BASE_WIDTH: 375,
  BASE_HEIGHT: 812,
  ISLAND_WIDTH: 126,
  ISLAND_HEIGHT: 36,
  HOME_BAR_WIDTH: 134,
  HOME_BAR_HEIGHT: 5,
  CORNER_RADIUS: 50,
  BORDER_WIDTH: 2,
  STATUS_BAR_HEIGHT: 44,
} as const;
