import {
  aiMlImage,
  dataScienceImage,
  fullStackImage,
  cloudDevopsImage,
} from "@/assets";

export interface Course {
  id: string;
  title: string;
  category: "Technology" | "Core Engineering" | "Data & AI" | "Design" | "Business" | "Career";
  description: string;
  price: number;
  originalPrice?: number;
  mode: "Online" | "Offline" | "Hybrid";
  isOnlineAvailable: boolean;
  duration: string;
  level: "Beginner to Advanced" | "Intermediate" | "All Levels";
  skills: string[];
  image: string;
  overview: string;
  outcomes: string[];
}

export const COURSES_DATA: Course[] = [
  // 1. AI & ML (Tech: ₹7,999 / was ₹9,999)
  {
    id: "ai-ml",
    title: "Artificial Intelligence & Machine Learning",
    category: "Data & AI",
    description: "Master neural networks, LLM prompt engineering, model fine-tuning, and computer vision with production Python deployments.",
    price: 7999,
    originalPrice: 9999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "14 Weeks",
    level: "Beginner to Advanced",
    skills: ["Python", "PyTorch", "HuggingFace", "Scikit-Learn", "FastAPI", "Docker"],
    image: aiMlImage,
    overview: "A comprehensive journey from linear algebra and supervised learning to deploying autonomous agents and transformers in production.",
    outcomes: ["Deploy 3 live machine learning systems", "Master LLM orchestration", "Verified capstone repository"],
  },
  // 2. Full Stack Web Development (Tech: ₹7,999 / was ₹9,999)
  {
    id: "web-dev",
    title: "Full Stack Web Engineering",
    category: "Technology",
    description: "Architect scalable web platforms using React 19, TypeScript, Node.js, PostgreSQL, and automated CI/CD cloud pipelines.",
    price: 7999,
    originalPrice: 9999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "14 Weeks",
    level: "Beginner to Advanced",
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "TailwindCSS", "Git"],
    image: fullStackImage,
    overview: "Build full-stack web applications with authentication, relational databases, distributed state management, and cloud hosting.",
    outcomes: ["Ship 2 production web apps", "Master modern React & Node.js", "Portfolio code reviews"],
  },
  // 3. Data Science & Predictive Analytics (Tech/Data: ₹7,999 / was ₹9,999)
  {
    id: "data-science",
    title: "Data Science & Predictive Analytics",
    category: "Data & AI",
    description: "Transform complex raw data into predictive algorithms, statistical models, interactive dashboards, and executive insights.",
    price: 7999,
    originalPrice: 9999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "12 Weeks",
    level: "Beginner to Advanced",
    skills: ["Python", "Pandas", "SQL", "Tableau", "Statistical Modeling", "BigQuery"],
    image: dataScienceImage,
    overview: "Develop deep fluency in data wrangling, hypothesis testing, regression pipelines, and business intelligence reporting.",
    outcomes: ["Build end-to-end data pipelines", "Publish interactive Tableau stories", "Predictive modeling certification"],
  },
  // 4. AutoCAD 2D & 3D Modeling (AutoCAD: ₹7,999)
  {
    id: "autocad",
    title: "AutoCAD 2D & 3D Precision Design",
    category: "Core Engineering",
    description: "Master architectural drafting, mechanical component modeling, precision dimensioning, and industrial blueprint generation.",
    price: 7999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "10 Weeks",
    level: "Beginner to Advanced",
    skills: ["AutoCAD 2D", "3D Modeling", "Isometric Drafting", "GD&T", "Blueprint Standards"],
    image: aiMlImage,
    overview: "From technical sketching fundamentals to multi-view orthographic projection and parametric 3D CAD modeling.",
    outcomes: ["Create 5 certified engineering blueprints", "Parametric mechanical assemblies", "Industry drafting certificate"],
  },
  // 5. Embedded Systems & Microcontrollers (Embedded: ₹7,999)
  {
    id: "embedded-systems",
    title: "Embedded Systems & Firmware Engineering",
    category: "Core Engineering",
    description: "Program ARM Cortex microcontrollers, RTOS kernels, communication protocols (SPI, I2C, UART), and hardware interfaces.",
    price: 7999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "12 Weeks",
    level: "Intermediate",
    skills: ["Embedded C", "ARM Cortex", "FreeRTOS", "UART / SPI / I2C", "Hardware Debugging"],
    image: fullStackImage,
    overview: "Low-level C firmware architecture, sensor drivers, interrupt handling, real-time operating systems, and hardware-software co-design.",
    outcomes: ["Build custom firmware drivers", "Deploy real-time RTOS tasks", "Hardware capstone proof"],
  },
  // 6. Internet of Things (IoT) & Robotics (Core Tech: ₹7,999)
  {
    id: "iot-robotics",
    title: "IoT Systems & Applied Robotics",
    category: "Core Engineering",
    description: "Design connected sensor networks, edge compute gateways, MQTT telemetry pipelines, and autonomous robotic actuators.",
    price: 7999,
    originalPrice: 9999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "12 Weeks",
    level: "Beginner to Advanced",
    skills: ["ESP32", "Arduino", "MQTT", "Python", "Sensor Integration", "Kinematics"],
    image: dataScienceImage,
    overview: "Connect physical microcontrollers to cloud backends, stream telemetry, process edge data, and control robotic subsystems.",
    outcomes: ["Build wireless IoT sensor node", "Autonomous obstacle robot", "Cloud IoT dashboard"],
  },
  // 7. VLSI Design & Verilog (Core Tech: ₹7,999)
  {
    id: "vlsi",
    title: "VLSI Digital Design & Verilog HDL",
    category: "Core Engineering",
    description: "Synthesize digital circuits, write Verilog HDL models, perform timing simulation, and design FPGA architectures.",
    price: 7999,
    originalPrice: 9999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "12 Weeks",
    level: "Intermediate",
    skills: ["Verilog HDL", "Digital Logic", "FPGA Architecture", "ModelSim", "Timing Analysis"],
    image: aiMlImage,
    overview: "RTL design principles, combinational and sequential circuit synthesis, testbench generation, and FPGA deployment workflows.",
    outcomes: ["Synthesize 3 custom RTL cores", "Comprehensive testbench coverage", "FPGA simulation proof"],
  },
  // 8. Cloud Computing & DevOps Architecture (Tech: ₹7,999 / was ₹9,999)
  {
    id: "cloud-devops",
    title: "Cloud Architecture & DevOps Systems",
    category: "Technology",
    description: "Automate containerized infrastructure with Docker, Kubernetes, Terraform IaC, AWS/GCP services, and GitHub Actions CI/CD.",
    price: 7999,
    originalPrice: 9999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "12 Weeks",
    level: "Beginner to Advanced",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "GitHub Actions", "Linux"],
    image: cloudDevopsImage,
    overview: "Master modern site reliability engineering, cloud infrastructure provisioning, microservice containerization, and zero-downtime deployments.",
    outcomes: ["Deploy multi-cluster Kubernetes apps", "Automated Terraform pipelines", "Cloud architecture portfolio"],
  },
  // 9. Cyber Security & Ethical Hacking (Tech: ₹7,999 / was ₹9,999)
  {
    id: "cyber-security",
    title: "Cyber Security & Defensive Operations",
    category: "Technology",
    description: "Learn network vulnerability assessment, penetration testing techniques, OWASP Top 10 web security, and threat mitigation.",
    price: 7999,
    originalPrice: 9999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "12 Weeks",
    level: "Beginner to Advanced",
    skills: ["Network Security", "Wireshark", "Kali Linux", "OWASP Top 10", "Penetration Testing"],
    image: fullStackImage,
    overview: "Defensive and offensive cyber methodologies, packet analysis, web application security auditing, and industry compliance frameworks.",
    outcomes: ["Perform security vulnerability audit", "Remediate web application exploits", "Security analyst certificate"],
  },
  // 10. Data Structures & Algorithms with Python (Tech: ₹7,999 / was ₹9,999)
  {
    id: "dsa-python",
    title: "DSA with Python & Interview Prep",
    category: "Technology",
    description: "Master computational problem solving, arrays, trees, graphs, dynamic programming, and asymptotic time-space analysis.",
    price: 7999,
    originalPrice: 9999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "10 Weeks",
    level: "Beginner to Advanced",
    skills: ["Python", "Algorithms", "Data Structures", "Dynamic Programming", "Time Complexity"],
    image: dataScienceImage,
    overview: "Rigorous coding practice across 150+ standard algorithm challenges with mock technical interviews and optimization reviews.",
    outcomes: ["Master 150+ algorithmic patterns", "Ace technical coding rounds", "Optimal complexity mindset"],
  },
  // 11. Android App Development with Kotlin (Tech: ₹7,999 / was ₹9,999)
  {
    id: "android-dev",
    title: "Android App Development with Kotlin",
    category: "Technology",
    description: "Build reactive Android mobile apps using Jetpack Compose, Kotlin coroutines, Room database, and REST API integration.",
    price: 7999,
    originalPrice: 9999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "12 Weeks",
    level: "Beginner to Advanced",
    skills: ["Kotlin", "Jetpack Compose", "Coroutines", "Room DB", "Retrofit", "Android Studio"],
    image: fullStackImage,
    overview: "Modern declarative Android UI design, MVVM architecture, background workers, and deploying production APKs to the Google Play Store.",
    outcomes: ["Publish 2 Android apps", "Master Jetpack Compose", "Play Store deployment proof"],
  },
  // 12. Hybrid & Electric Vehicle Engineering (Core Tech: ₹7,999)
  {
    id: "hev",
    title: "Hybrid Electric Vehicle (HEV) Technology",
    category: "Core Engineering",
    description: "Understand EV powertrain architectures, battery management systems (BMS), regenerative braking, and motor controllers.",
    price: 7999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "10 Weeks",
    level: "Beginner to Advanced",
    skills: ["EV Powertrain", "BMS Architecture", "Lithium-ion Chemistries", "MATLAB / Simulink", "Motor Drives"],
    image: aiMlImage,
    overview: "Detailed engineering of electric vehicle drive systems, thermal battery management, inverter electronics, and charging standards.",
    outcomes: ["Simulate EV drive cycle in MATLAB", "BMS algorithm design", "EV technology certification"],
  },
  // 13. UI/UX & Interactive Product Design (Design / Non-Tech: ₹6,999)
  {
    id: "ui-ux",
    title: "UI/UX & Interactive Product Design",
    category: "Design",
    description: "Create user research syntheses, wireframes, high-fidelity prototypes in Figma, design systems, and usability test plans.",
    price: 6999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "10 Weeks",
    level: "Beginner to Advanced",
    skills: ["Figma", "Design Systems", "User Research", "Wireframing", "Prototyping", "Usability Testing"],
    image: fullStackImage,
    overview: "End-to-end UX discovery, information architecture, responsive UI components, micro-animations, and complete case study portfolios.",
    outcomes: ["Design 2 full product case studies", "Publish Figma component library", "Verified UI/UX portfolio"],
  },
  // 14. Graphic Designing & Visual Brand Systems (Design / Non-Tech: ₹6,999)
  {
    id: "graphic-design",
    title: "Graphic Design & Visual Brand Systems",
    category: "Design",
    description: "Master typography, color theory, editorial layouts, vector illustration, and brand guidelines using industry design suites.",
    price: 6999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "8 Weeks",
    level: "Beginner to Advanced",
    skills: ["Photoshop", "Illustrator", "Typography", "Color Theory", "Brand Identity", "Editorial Design"],
    image: dataScienceImage,
    overview: "Develop high-craft brand identities, promotional collateral, digital vector illustrations, and print-ready publishing assets.",
    outcomes: ["Create complete brand identity system", "10-piece visual design portfolio", "Design asset library"],
  },
  // 15. Digital Marketing & Growth Strategy (Non-Tech: ₹6,999)
  {
    id: "digital-marketing",
    title: "Digital Marketing & Performance Growth",
    category: "Business",
    description: "Run data-driven growth campaigns, master technical SEO, paid Google/Meta ads, content funnels, and marketing analytics.",
    price: 6999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "10 Weeks",
    level: "Beginner to Advanced",
    skills: ["SEO Strategy", "Google Ads", "Meta Ads", "Content Funnels", "Google Analytics 4", "Email Marketing"],
    image: cloudDevopsImage,
    overview: "Campaign optimization, CAC/LTV unit economics, keyword research, conversion rate optimization, and multichannel growth strategies.",
    outcomes: ["Manage live ad simulation campaigns", "Audit enterprise SEO performance", "Growth marketing certification"],
  },
  // 16. Business Analysis & Requirements Engineering (Non-Tech: ₹6,999)
  {
    id: "business-analysis",
    title: "Business Analysis & Data Strategy",
    category: "Business",
    description: "Bridge stakeholders and technical squads with agile user stories, process flows (BPMN), market research, and financial metrics.",
    price: 6999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "10 Weeks",
    level: "Beginner to Advanced",
    skills: ["BPMN", "Agile User Stories", "Requirements Engineering", "SQL Basics", "Tableau", "Jira"],
    image: dataScienceImage,
    overview: "Translate executive business goals into structured engineering requirements, backlog prioritization, and functional specifications.",
    outcomes: ["Author comprehensive BRD/FRD", "BPMN process optimization case study", "Business analyst certificate"],
  },
  // 17. Finance & Investment Analysis (Non-Tech: ₹6,999)
  {
    id: "finance",
    title: "Corporate Finance & Valuation Modeling",
    category: "Business",
    description: "Construct three-statement financial models, discounted cash flow (DCF) valuations, and corporate financial health scorecards.",
    price: 6999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "10 Weeks",
    level: "Beginner to Advanced",
    skills: ["Financial Modeling", "Excel DCF", "Statement Analysis", "Valuation", "Ratio Analysis"],
    image: aiMlImage,
    overview: "Master Excel financial modeling, equity valuation techniques, capital budgeting decisions, and risk-return management.",
    outcomes: ["Build 3 live DCF valuation models", "Corporate financial diagnostic report", "Finance analyst certificate"],
  },
  // 18. Stock Market Trading & Technical Analysis (Non-Tech: ₹6,999)
  {
    id: "stock-market",
    title: "Stock Market Trading & Technical Analysis",
    category: "Business",
    description: "Understand chart patterns, candlestick indicators, risk-reward ratios, portfolio diversification, and market microstructure.",
    price: 6999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "8 Weeks",
    level: "Beginner to Advanced",
    skills: ["Technical Analysis", "Price Action", "Risk Management", "Options Basics", "Portfolio Sizing"],
    image: fullStackImage,
    overview: "Systematic trading strategies, fundamental screening metrics, risk mitigation rules, and disciplined execution psychology.",
    outcomes: ["Develop systematic trading plan", "Risk-managed backtest portfolio", "Market analysis proof"],
  },
  // 19. Product & Project Management (Non-Tech: ₹6,999)
  {
    id: "product-management",
    title: "Product & Agile Project Management",
    category: "Business",
    description: "Lead product discovery sprints, define PRDs, manage sprint ceremonies in Jira, and drive go-to-market product launches.",
    price: 6999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "10 Weeks",
    level: "Beginner to Advanced",
    skills: ["Product Roadmap", "PRD Authoring", "Scrum / Agile", "Jira", "GTM Strategy", "User Interviews"],
    image: cloudDevopsImage,
    overview: "From customer problem validation and competitive analysis to sprint planning, roadmap execution, and launch metrics.",
    outcomes: ["Author complete Product Requirement Document (PRD)", "Lead mock agile sprint", "PM portfolio proof"],
  },
  // 20. Human Resource Management (Non-Tech: ₹6,999)
  {
    id: "hrm",
    title: "Human Resource Management & Talent Strategy",
    category: "Career",
    description: "Master modern talent acquisition, HR analytics, performance appraisal systems, employee engagement, and labor compliance.",
    price: 6999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "8 Weeks",
    level: "Beginner to Advanced",
    skills: ["Talent Acquisition", "HR Analytics", "Performance Systems", "Labor Law Compliance", "Onboarding Workflows"],
    image: fullStackImage,
    overview: "Strategic workforce planning, metric-driven hiring pipelines, employee retention programs, and modern HR tech stacks.",
    outcomes: ["Design end-to-end recruitment funnel", "HR metrics dashboard", "HR professional certificate"],
  },
  // 21. Psychology & Applied Behavioral Analysis (Non-Tech: ₹6,999)
  {
    id: "psychology",
    title: "Applied Psychology & Behavioral Science",
    category: "Career",
    description: "Explore cognitive psychology principles, organizational behavior, interpersonal communication, and decision-making science.",
    price: 6999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "8 Weeks",
    level: "All Levels",
    skills: ["Cognitive Science", "Behavioral Analysis", "Interpersonal Communication", "Research Methods"],
    image: dataScienceImage,
    overview: "Application of psychological concepts to personal development, workplace dynamics, user decision heuristics, and counseling fundamentals.",
    outcomes: ["Behavioral research study report", "Cognitive heuristics framework", "Applied psychology certificate"],
  },
  // 22. Medical Coding & Healthcare Informatics (Non-Tech: ₹6,999)
  {
    id: "medical-coding",
    title: "Medical Coding & Healthcare Classification",
    category: "Career",
    description: "Master ICD-10-CM, CPT, and HCPCS medical diagnostic coding standards, HIPAA healthcare compliance, and claims processing.",
    price: 6999,
    mode: "Online",
    isOnlineAvailable: true,
    duration: "10 Weeks",
    level: "Beginner to Advanced",
    skills: ["ICD-10-CM", "CPT Coding", "HCPCS", "HIPAA Compliance", "Medical Terminology", "Claims Review"],
    image: aiMlImage,
    overview: "Comprehensive clinical classification, patient records auditing, medical terminology, and insurance reimbursement workflows.",
    outcomes: ["Code 50+ real clinical case records", "ICD-10 / CPT practice mastery", "Medical coding certification"],
  },
];
